# Generated by Django 4.1 on 2022-08-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='mensaje',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='titulo',
            new_name='title',
        ),
    ]
